# Generated by Django 4.0.1 on 2022-01-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
